### ISSUE TITLE
Please, set tags for releases

### ISSUE THREAD

**Issue by eribertomota** [brendangregg/Chaosreader#4]
Hi Brendan,

I am the chaosreader maintainer in Debian. Can you set releases in GitHub? It is usefull to allow to Debian and other distros to monitor changes in chaosreader.

The chaosreader version in several distros is 0.94[1] because no one was able to find the current 0.96 version. I will package 0.96 today in Debian.

[1] http://beta.repology.org/maintainers/joao_eriberto_mota_filho__eriberto@debian.org_.0.html

Thanks a lot in advance!

Regards,

Eriberto

**Comment by AMDmi3** [comment]
Up to date repology URL is http://repology.org/metapackages/all/?search=chaosreader

**Comment by brendangregg** [comment]
Ok, thanks, I need to double check that the latest really is here, and then learn how to set GitHub release tags. :)

**Comment by eribertomota** [comment]
2016-12-29 19:45 GMT-02:00 Brendan Gregg <notifications@github.com>:

> Ok, thanks, I need to double check that the latest really is here, and
> then learn how to set GitHub release tags. :)
>

Hi Brendan,

To release a tag is very easy.

1. Go to https://github.com/brendangregg/Chaosreader

2. Click over releases (near commits / branch / contributor).

3. Click over 'Draft a new release'.

4. In the box near @ Target: master write 0.96.

5. Click over 'Publish release'.

See an example of the final results here:

https://github.com/eribertomota/axel/releases


The current version in GitHub is 0.96. See here:

https://github.com/brendangregg/Chaosreader/blob/master/chaosreader


To put a tag in an old version, as 0.94, you will need to use the git
command. I can help if you want.

Cheers,

Eriberto

**Comment by brendangregg** [comment]
Thanks Eriberto, done! I like how it created a .tar.gz too.

**Comment by eribertomota** [comment]
2017-01-04 18:36 GMT-02:00 Brendan Gregg <notifications@github.com>:

> Thanks Eriberto, done! I like how it created a .tar.gz too.
>

Cool!!! I uploaded a reviewed package to Debian. Now , Debian will know
when you release a new version.

Cheers,

Eriberto

**Comment by AMDmi3** [comment]
Thank you!
